module.exports = async (client, guild) => {
    await client.db.bans.destroy({ where: { guildID: guild.id } })
    await client.db.crowns.destroy({ where: { guildID: guild.id } })
    await client.db.prefix.destroy({ where: { guildID: guild.id } })
    await client.db.afk.destroy({ where: { guildID: guild.id } })
    await client.db.boost_channel.destroy({ where: { guildID: guild.id } })
    await client.db.boost_message.destroy({ where: { guildID: guild.id } })
    await client.db.media_channel.destroy({ where: { guildID: guild.id } })
    await client.db.welcome_channel.destroy({ where: { guildID: guild.id } })
    await client.db.welcome_embed.destroy({ where: { guildID: guild.id } })
    await client.db.welcome_message.destroy({ where: { guildID: guild.id } })
    await client.db.mute_role.destroy({ where: { guildID: guild.id } })
    await client.db.vanity_role.destroy({ where: { guildID: guild.id } })
    await client.db.vanity_message.destroy({ where: { guildID: guild.id } })
    await client.db.vanity_status.destroy({ where: { guildID: guild.id } })
    await client.db.vanity_channel.destroy({ where: { guildID: guild.id } })
    await client.db.starboard.destroy({ where: { guildID: guild.id } })
    await client.db.starboard_emoji.destroy({ where: { guildID: guild.id } })
    await client.db.jail_role.destroy({ where: { guildID: guild.id } })
    await client.db.jail_channel.destroy({ where: { guildID: guild.id } })
    await client.db.jail_message.destroy({ where: { guildID: guild.id } })
    await client.db.jailed.destroy({ where: { guildID: guild.id } })
    await client.db.muted.destroy({ where: { guildID: guild.id } })
    await client.db.updates.destroy({ where: { guildID: guild.id } })
    await client.db.toggled_commands.destroy({ where: { guildID: guild.id } })
    await client.db.command_whitelists.destroy({ where: { guildID: guild.id } })
    await client.db.history.destroy({ where: { guildID: guild.id } })
    client.logger.info(`Left ${guild.name} (${guild.id}) cleared Database.`)
}